name: Deploy Example

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: sfdx-test-run
        run: |
           sfdx force:source:deploy -p force-app/ -l RunLocalTests -w 30
           sfdx force:apex:execute -f scripts/apex/RunRelease.apex
